### ISSUE TITLE
有没有办法在js中自动获取运行该js的GameObject

### ISSUE THREAD

**Issue by cloudending** [ialex32x/duktape-unity#31]
目前使用的都是
```
GameObject.Find("xxx") 
```
这样的方式来找一个GameObject。
如何在js里面，自动获取GameObject呢，就像挂在GameObject上的c#脚本

**Comment by ialex32x** [comment]
这个没办法提供, js 跟 GameObject 本身并没有直接的关联关系. 
如果需要在脚本中做一些类似 MonoBehaviour 的功能考虑用 DuktapeJS.Bridge
```js
    let gameObject = new GameObject("test");
    let bridge = gameObject.AddComponent(DuktapeJS.Bridge)
    let target = new MyCircleBridge();
    target.gameObject = bridge.gameObject;
    target.transform = bridge.transform;
    bridge.SetBridge(target);
```
不过不建议大量使用 Bridge, 跨域交互效率比较低. 一般创建一个, 之后基于其 Update, 在脚本中实现独立的逻辑, 不要直接使用 MonoBehaviour 的思路.
